version: '3'

networks:
    graylog:
        driver: bridge

services:
  hash-calc-service:
    build:
      context: server
    ports:
      - "8090:8090"
      - "7755:7755"
    restart: on-failure
    depends_on:
      - postgres
  hash-calc-client:
    build:
      context: client
    ports:
      - "8080:8080"
      - "7766:7766"
    restart: on-failure
    depends_on:
      - hash-calc-service
  postgres:
    image: postgres
    tty: true
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=hashdb
    volumes:
      - ./prod/postgres-data:/var/lib/postgresql/data
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - 9090:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yaml
    volumes:
      - ./prod/prometheus.yaml:/etc/prometheus/prometheus.yaml:ro
  grafana:
    image: grafana/grafana:latest
    links:
      - prometheus:prometheus
    volumes:
      - ./prod/grafana:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin # nen логин для входа
      - GF_SECURITY_ADMIN_PASSWORD=admin #тут значения пароля для входа 
      - GF_USERS_ALLOW_SIGN_UP=false
    ports:
      - 3000:3000
  mongo:
    image: mongo:3
    networks:
    - graylog
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.8.10
    environment:
    - http.host=0.0.0.0
    - transport.host=localhost
    - network.host=0.0.0.0
    - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    # ulimits: 65535
    # memlock:
    #     soft: -1
    #     hard: -1
    deploy:
    # resources:
    #     limits:
    #     memory: 1g
    networks:
    - graylog
  graylog:
    image: graylog/graylog:3.3
    environment:
    - GRAYLOG_PASSWORD_SECRET=somepasswordpepper
    - GRAYLOG_ROOT_PASSWORD_SHA2=8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918
    - GRAYLOG_HTTP_EXTERNAL_URI=http://graylog:9000/
    networks:
    - graylog
    depends_on:
    - mongo
    - elasticsearch
    ports:
    # Graylog web interface and REST API
    - 9000:9000
    # Syslog TCP
    - 1514:1514
    # Syslog UDP
    - 1514:1514/udp
    # GELF TCP
    - 12201:12201
    # GELF UDP
    - 12201:12201/udp      