// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: protoc/hashCalc.proto

package hashcalc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TextList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines []string `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
}

func (x *TextList) Reset() {
	*x = TextList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_hashCalc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TextList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TextList) ProtoMessage() {}

func (x *TextList) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_hashCalc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TextList.ProtoReflect.Descriptor instead.
func (*TextList) Descriptor() ([]byte, []int) {
	return file_protoc_hashCalc_proto_rawDescGZIP(), []int{0}
}

func (x *TextList) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

var File_protoc_hashCalc_proto protoreflect.FileDescriptor

var file_protoc_hashCalc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x20, 0x0a, 0x08, 0x54, 0x65, 0x78, 0x74,
	0x4c, 0x69, 0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x32, 0x4e, 0x0a, 0x08, 0x48, 0x61,
	0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x12, 0x42, 0x0a, 0x08, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x48,
	0x41, 0x33, 0x12, 0x19, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x54, 0x65, 0x78, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x19, 0x2e,
	0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x54, 0x65, 0x78, 0x74, 0x4c, 0x69, 0x73, 0x74, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f,
	0x70, 0x6b, 0x67, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x63, 0x61, 0x6c, 0x63, 0x3b, 0x68, 0x61, 0x73,
	0x68, 0x63, 0x61, 0x6c, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_hashCalc_proto_rawDescOnce sync.Once
	file_protoc_hashCalc_proto_rawDescData = file_protoc_hashCalc_proto_rawDesc
)

func file_protoc_hashCalc_proto_rawDescGZIP() []byte {
	file_protoc_hashCalc_proto_rawDescOnce.Do(func() {
		file_protoc_hashCalc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_hashCalc_proto_rawDescData)
	})
	return file_protoc_hashCalc_proto_rawDescData
}

var file_protoc_hashCalc_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_protoc_hashCalc_proto_goTypes = []interface{}{
	(*TextList)(nil), // 0: HashCalcService.TextList
}
var file_protoc_hashCalc_proto_depIdxs = []int32{
	0, // 0: HashCalcService.HashCalc.CalcSHA3:input_type -> HashCalcService.TextList
	0, // 1: HashCalcService.HashCalc.CalcSHA3:output_type -> HashCalcService.TextList
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protoc_hashCalc_proto_init() }
func file_protoc_hashCalc_proto_init() {
	if File_protoc_hashCalc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_hashCalc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TextList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_hashCalc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_hashCalc_proto_goTypes,
		DependencyIndexes: file_protoc_hashCalc_proto_depIdxs,
		MessageInfos:      file_protoc_hashCalc_proto_msgTypes,
	}.Build()
	File_protoc_hashCalc_proto = out.File
	file_protoc_hashCalc_proto_rawDesc = nil
	file_protoc_hashCalc_proto_goTypes = nil
	file_protoc_hashCalc_proto_depIdxs = nil
}
