server:
  name: Compute hash server
  host: 0.0.0.0
  port: 8090
  worker-count: 5
  cache-count: 5
  db:
    # Supported DB type is postgres only
    type: postgres
    pool-count: 5
    host: postgres
    port: 5432
    user: postgres
    pass: postgres
    dbname: hashdb
    ssl: disable
metric:
  host: 0.0.0.0
  port: 7755
  path: metrics
logging:
  provider: graylog
  host: graylog
  port: 12201
  level: 5
