// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.30.0
// 	protoc        v4.22.2
// source: protoc/hashCalc.proto

package hashcalc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Hash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id   int64  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Hash string `protobuf:"bytes,2,opt,name=hash,proto3" json:"hash,omitempty"`
}

func (x *Hash) Reset() {
	*x = Hash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_hashCalc_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Hash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hash) ProtoMessage() {}

func (x *Hash) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_hashCalc_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hash.ProtoReflect.Descriptor instead.
func (*Hash) Descriptor() ([]byte, []int) {
	return file_protoc_hashCalc_proto_rawDescGZIP(), []int{0}
}

func (x *Hash) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Hash) GetHash() string {
	if x != nil {
		return x.Hash
	}
	return ""
}

type StringList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines []string `protobuf:"bytes,1,rep,name=lines,proto3" json:"lines,omitempty"`
}

func (x *StringList) Reset() {
	*x = StringList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_hashCalc_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *StringList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StringList) ProtoMessage() {}

func (x *StringList) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_hashCalc_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StringList.ProtoReflect.Descriptor instead.
func (*StringList) Descriptor() ([]byte, []int) {
	return file_protoc_hashCalc_proto_rawDescGZIP(), []int{1}
}

func (x *StringList) GetLines() []string {
	if x != nil {
		return x.Lines
	}
	return nil
}

type IDList struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Lines []int64 `protobuf:"varint,1,rep,packed,name=lines,proto3" json:"lines,omitempty"`
}

func (x *IDList) Reset() {
	*x = IDList{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_hashCalc_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IDList) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IDList) ProtoMessage() {}

func (x *IDList) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_hashCalc_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IDList.ProtoReflect.Descriptor instead.
func (*IDList) Descriptor() ([]byte, []int) {
	return file_protoc_hashCalc_proto_rawDescGZIP(), []int{2}
}

func (x *IDList) GetLines() []int64 {
	if x != nil {
		return x.Lines
	}
	return nil
}

type ArrayHash struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Hash []*Hash `protobuf:"bytes,1,rep,name=hash,proto3" json:"hash,omitempty"`
}

func (x *ArrayHash) Reset() {
	*x = ArrayHash{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protoc_hashCalc_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ArrayHash) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ArrayHash) ProtoMessage() {}

func (x *ArrayHash) ProtoReflect() protoreflect.Message {
	mi := &file_protoc_hashCalc_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ArrayHash.ProtoReflect.Descriptor instead.
func (*ArrayHash) Descriptor() ([]byte, []int) {
	return file_protoc_hashCalc_proto_rawDescGZIP(), []int{3}
}

func (x *ArrayHash) GetHash() []*Hash {
	if x != nil {
		return x.Hash
	}
	return nil
}

var File_protoc_hashCalc_proto protoreflect.FileDescriptor

var file_protoc_hashCalc_proto_rawDesc = []byte{
	0x0a, 0x15, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c,
	0x63, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0f, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c,
	0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x22, 0x2a, 0x0a, 0x04, 0x48, 0x61, 0x73, 0x68,
	0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x68, 0x61, 0x73, 0x68, 0x22, 0x22, 0x0a, 0x0a, 0x53, 0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x1e, 0x0a, 0x06, 0x49, 0x44, 0x4c, 0x69,
	0x73, 0x74, 0x12, 0x14, 0x0a, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28,
	0x03, 0x52, 0x05, 0x6c, 0x69, 0x6e, 0x65, 0x73, 0x22, 0x36, 0x0a, 0x09, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x12, 0x29, 0x0a, 0x04, 0x68, 0x61, 0x73, 0x68, 0x18, 0x01, 0x20,
	0x03, 0x28, 0x0b, 0x32, 0x15, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x65,
	0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x52, 0x04, 0x68, 0x61, 0x73, 0x68,
	0x32, 0x96, 0x01, 0x0a, 0x08, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x12, 0x48, 0x0a,
	0x0b, 0x43, 0x6f, 0x6d, 0x70, 0x75, 0x74, 0x65, 0x48, 0x61, 0x73, 0x68, 0x12, 0x1b, 0x2e, 0x48,
	0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x53,
	0x74, 0x72, 0x69, 0x6e, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x48, 0x61, 0x73, 0x68,
	0x43, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x72, 0x72, 0x61,
	0x79, 0x48, 0x61, 0x73, 0x68, 0x22, 0x00, 0x12, 0x40, 0x0a, 0x07, 0x47, 0x65, 0x74, 0x48, 0x61,
	0x73, 0x68, 0x12, 0x17, 0x2e, 0x48, 0x61, 0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72,
	0x76, 0x69, 0x63, 0x65, 0x2e, 0x49, 0x44, 0x4c, 0x69, 0x73, 0x74, 0x1a, 0x1a, 0x2e, 0x48, 0x61,
	0x73, 0x68, 0x43, 0x61, 0x6c, 0x63, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e, 0x41, 0x72,
	0x72, 0x61, 0x79, 0x48, 0x61, 0x73, 0x68, 0x22, 0x00, 0x42, 0x19, 0x5a, 0x17, 0x2e, 0x2f, 0x70,
	0x6b, 0x67, 0x2f, 0x68, 0x61, 0x73, 0x68, 0x63, 0x61, 0x6c, 0x63, 0x3b, 0x68, 0x61, 0x73, 0x68,
	0x63, 0x61, 0x6c, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protoc_hashCalc_proto_rawDescOnce sync.Once
	file_protoc_hashCalc_proto_rawDescData = file_protoc_hashCalc_proto_rawDesc
)

func file_protoc_hashCalc_proto_rawDescGZIP() []byte {
	file_protoc_hashCalc_proto_rawDescOnce.Do(func() {
		file_protoc_hashCalc_proto_rawDescData = protoimpl.X.CompressGZIP(file_protoc_hashCalc_proto_rawDescData)
	})
	return file_protoc_hashCalc_proto_rawDescData
}

var file_protoc_hashCalc_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protoc_hashCalc_proto_goTypes = []interface{}{
	(*Hash)(nil),       // 0: HashCalcService.Hash
	(*StringList)(nil), // 1: HashCalcService.StringList
	(*IDList)(nil),     // 2: HashCalcService.IDList
	(*ArrayHash)(nil),  // 3: HashCalcService.ArrayHash
}
var file_protoc_hashCalc_proto_depIdxs = []int32{
	0, // 0: HashCalcService.ArrayHash.hash:type_name -> HashCalcService.Hash
	1, // 1: HashCalcService.HashCalc.ComputeHash:input_type -> HashCalcService.StringList
	2, // 2: HashCalcService.HashCalc.GetHash:input_type -> HashCalcService.IDList
	3, // 3: HashCalcService.HashCalc.ComputeHash:output_type -> HashCalcService.ArrayHash
	3, // 4: HashCalcService.HashCalc.GetHash:output_type -> HashCalcService.ArrayHash
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protoc_hashCalc_proto_init() }
func file_protoc_hashCalc_proto_init() {
	if File_protoc_hashCalc_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protoc_hashCalc_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Hash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_hashCalc_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*StringList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_hashCalc_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IDList); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protoc_hashCalc_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ArrayHash); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protoc_hashCalc_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protoc_hashCalc_proto_goTypes,
		DependencyIndexes: file_protoc_hashCalc_proto_depIdxs,
		MessageInfos:      file_protoc_hashCalc_proto_msgTypes,
	}.Build()
	File_protoc_hashCalc_proto = out.File
	file_protoc_hashCalc_proto_rawDesc = nil
	file_protoc_hashCalc_proto_goTypes = nil
	file_protoc_hashCalc_proto_depIdxs = nil
}
