// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.22.2
// source: protoc/hashCalc.proto

package hashcalc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	HashCalc_ComputeHash_FullMethodName = "/HashCalcService.HashCalc/ComputeHash"
	HashCalc_GetHash_FullMethodName     = "/HashCalcService.HashCalc/GetHash"
)

// HashCalcClient is the client API for HashCalc service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type HashCalcClient interface {
	ComputeHash(ctx context.Context, in *StringList, opts ...grpc.CallOption) (*ArrayHash, error)
	GetHash(ctx context.Context, in *IDList, opts ...grpc.CallOption) (*ArrayHash, error)
}

type hashCalcClient struct {
	cc grpc.ClientConnInterface
}

func NewHashCalcClient(cc grpc.ClientConnInterface) HashCalcClient {
	return &hashCalcClient{cc}
}

func (c *hashCalcClient) ComputeHash(ctx context.Context, in *StringList, opts ...grpc.CallOption) (*ArrayHash, error) {
	out := new(ArrayHash)
	err := c.cc.Invoke(ctx, HashCalc_ComputeHash_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *hashCalcClient) GetHash(ctx context.Context, in *IDList, opts ...grpc.CallOption) (*ArrayHash, error) {
	out := new(ArrayHash)
	err := c.cc.Invoke(ctx, HashCalc_GetHash_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// HashCalcServer is the server API for HashCalc service.
// All implementations must embed UnimplementedHashCalcServer
// for forward compatibility
type HashCalcServer interface {
	ComputeHash(context.Context, *StringList) (*ArrayHash, error)
	GetHash(context.Context, *IDList) (*ArrayHash, error)
	mustEmbedUnimplementedHashCalcServer()
}

// UnimplementedHashCalcServer must be embedded to have forward compatible implementations.
type UnimplementedHashCalcServer struct {
}

func (UnimplementedHashCalcServer) ComputeHash(context.Context, *StringList) (*ArrayHash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ComputeHash not implemented")
}
func (UnimplementedHashCalcServer) GetHash(context.Context, *IDList) (*ArrayHash, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetHash not implemented")
}
func (UnimplementedHashCalcServer) mustEmbedUnimplementedHashCalcServer() {}

// UnsafeHashCalcServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to HashCalcServer will
// result in compilation errors.
type UnsafeHashCalcServer interface {
	mustEmbedUnimplementedHashCalcServer()
}

func RegisterHashCalcServer(s grpc.ServiceRegistrar, srv HashCalcServer) {
	s.RegisterService(&HashCalc_ServiceDesc, srv)
}

func _HashCalc_ComputeHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StringList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashCalcServer).ComputeHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashCalc_ComputeHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashCalcServer).ComputeHash(ctx, req.(*StringList))
	}
	return interceptor(ctx, in, info, handler)
}

func _HashCalc_GetHash_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IDList)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(HashCalcServer).GetHash(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: HashCalc_GetHash_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(HashCalcServer).GetHash(ctx, req.(*IDList))
	}
	return interceptor(ctx, in, info, handler)
}

// HashCalc_ServiceDesc is the grpc.ServiceDesc for HashCalc service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var HashCalc_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "HashCalcService.HashCalc",
	HandlerType: (*HashCalcServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ComputeHash",
			Handler:    _HashCalc_ComputeHash_Handler,
		},
		{
			MethodName: "GetHash",
			Handler:    _HashCalc_GetHash_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protoc/hashCalc.proto",
}
